name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install --legacy-peer-deps

    - name: Build
      run: |
        echo "INFURA_API_KEY=${{ secrets.INFURA_API_KEY }}" > .env
        echo "PRIVATE_KEY=${{ secrets.PRIVATE_KEY }}" >> .env
        npm run build

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.2.1
      with:
        branch: gh-pages
        folder: dist
        token: ${{ secrets.GITHUB_TOKEN }}
