name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install --legacy-peer-deps

    - name: Build
      env:
          API_KEY: ${{ secrets.API_KEY }}
      run: 
          npm run build
          npm run deploy

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.2.1
      with:
        branch: gh-pages
        folder: dist
        token: ${{ secrets.API_KEY }}
